resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/00487726c4bc21b4744e59d913334ebfeac7d68e/snapshot.yaml

packages:
  - .

extra-deps:

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: dbd932704fa4520bc24e45b2c00407c5f437c12a
    subdirs:
      - iohk-monitoring
      - contra-tracer
      - plugins/backend-ekg
      - tracer-transformers

  - git: https://github.com/input-output-hk/cardano-base
    commit: 80deee31f8d9422b8e090e55b17e1a714153180b
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class
      - slotting

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: a773ba71eb9a6fb91dda2cdf6c41b2280f2acf7d
    subdirs:
      - cardano-ledger
      - crypto

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 00487726c4bc21b4744e59d913334ebfeac7d68e
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-shell
    commit: bc3563c952d9f3635e1c76749b86b0a24f7e4b83
    subdirs:
      - cardano-shell

  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: f9e3da6c51fcb902266b9c8b2678cd5f2b665a8c
    subdirs:
      - ouroboros-consensus
      - ouroboros-network
      - io-sim-classes
      - network-mux
      - typed-protocols
      - typed-protocols-cbor

  - bimap-0.4.0
  - binary-0.8.7.0
  - containers-0.5.11.0
  - ekg-prometheus-adapter-0.1.0.4
  - generic-monoid-0.1.0.0
  - graphviz-2999.20.0.3@sha256:cde383c356bc41136ed53cd27e0800f46dbd2185600dd0de18d66d5c49739d94
  - libsystemd-journal-1.4.4
  - prometheus-2.1.2
  - quickcheck-state-machine-0.6.0@sha256:3e4f8df0f6b5d415e3c8840dc75034a63e37f56f5f8cfa1035ded16345235ac4
  - splitmix-0.0.2
  - tasty-hedgehog-1.0.0.1
  - time-units-1.0.0
  - katip-0.8.3.0
  - statistics-linreg-0.3

  # Windows only
  - Win32-2.5.4.1

  # The parts of cardano-sl that are needed for the byron proxy.
  - git: https://github.com/input-output-hk/cardano-sl
    commit: 37d38f71c36bec13ddf8c664c567d7ae122f5923
    subdirs:
      - lib
      - binary
      - binary/test
      - util
      - util/test
      - infra
      - infra/test
      - core
      - core/test
      - chain
      - chain/test
      - db
      - db/test
      - crypto
      - crypto/test
      - networking

  - git: https://github.com/input-output-hk/log-warper
    commit: 16246d4fbf16da7984f2a4b6c42f2ed5098182e4

  - git: https://github.com/input-output-hk/rocksdb-haskell-ng
    commit: 49f501a082d745f3b880677220a29cafaa181452

  - git: https://github.com/avieth/kademlia
    commit: 38a0575bb303804461f4b6176ca38eba81adbd79

  - git: https://github.com/serokell/network-transport
    commit: 018a50b9042c2115c3ec9c9fd5ca5f28737dd29c

  - git: https://github.com/avieth/network-transport-tcp
    commit: 984386467466d89621eda1cff8bbb435a9b9c0ef

  - git: https://github.com/input-output-hk/universum
    commit: 15f7db758ff5a24b874de2247f6f7a4576562da5

  - git: https://github.com/input-output-hk/serokell-util
    commit: 457f1d149c6e238841f283a1faf7bc8fb021b27d

  - git: https://github.com/input-output-hk/ether
    commit: a311878ae17ed5f201421bdcd5392a24b746ff0b

  - git: https://github.com/input-output-hk/transformers-lift
    commit: c830bc7e7e41895e3c50488a92d34405b68b4ad8

  - aeson-options-0.1.0
  - pvss-0.2.0
  - lrucache-1.2.0.1
  - writer-cps-mtl-0.1.1.6
  - writer-cps-transformers-0.5.6.0
  - o-clock-1.0.0.1
  - ekg-wai-0.1.0.3
  - lzma-clib-5.2.2

  - network-3.1.0.1
  - systemd-2.0.0
  - socks-0.6.0
  - connection-0.3.0
  - snap-server-1.1.1.1
  - swagger2-2.4
  # Needed by swagger2 version (InsOrd module)
  - insert-ordered-containers-0.2.2
  # Neede because of swagger2
  - servant-swagger-1.1.7.1
  # Needed because of servant-swagger
  - servant-0.15
  - servant-client-0.15
  - servant-client-core-0.15
  - servant-server-0.15

ghc-options:
  cardano-byron-proxy:     -Wall -Werror -Wcompat -fwarn-redundant-constraints -fwarn-incomplete-patterns -fwarn-unused-imports -Wincomplete-record-updates -Wincomplete-uni-patterns

nix:
  shell-file: nix/stack-shell.nix
